/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Rotchford.Daniel.hello;

import java.awt.geom.Point2D;
import java.util.Arrays;

/**
 *
 * @author Daniel
 */
public class GraphFrame extends javax.swing.JFrame {

    /**
     * Creates new form GraphFrame
     */
    String posNeg;
    public GraphFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        X0Textfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Y0Textfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        X1Textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Y1Textfield = new javax.swing.JTextField();
        CalculateButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textBox = new javax.swing.JTextArea();
        X0Textfield2 = new javax.swing.JTextField();
        Y0Textfield2 = new javax.swing.JTextField();
        Y1Textfield2 = new javax.swing.JTextField();
        X1Textfield2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equation of a Line");

        jLabel1.setText("x0");

        X0Textfield.setText("0");
        X0Textfield.setToolTipText("");
        X0Textfield.setPreferredSize(new java.awt.Dimension(60, 25));
        X0Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X0TextfieldActionPerformed(evt);
            }
        });

        jLabel2.setText("y0");

        Y0Textfield.setText("0");
        Y0Textfield.setToolTipText("");
        Y0Textfield.setPreferredSize(new java.awt.Dimension(60, 25));
        Y0Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y0TextfieldActionPerformed(evt);
            }
        });

        jLabel3.setText("x1");

        X1Textfield.setText("0");
        X1Textfield.setToolTipText("");
        X1Textfield.setPreferredSize(new java.awt.Dimension(60, 25));
        X1Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X1TextfieldActionPerformed(evt);
            }
        });

        jLabel4.setText("y1");

        Y1Textfield.setText("0");
        Y1Textfield.setToolTipText("");
        Y1Textfield.setPreferredSize(new java.awt.Dimension(60, 25));
        Y1Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y1TextfieldActionPerformed(evt);
            }
        });

        CalculateButton.setText("Calculate");
        CalculateButton.setName("CalculateButton"); // NOI18N
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        textBox.setColumns(20);
        textBox.setRows(5);
        jScrollPane1.setViewportView(textBox);

        X0Textfield2.setText("0");
        X0Textfield2.setToolTipText("");
        X0Textfield2.setPreferredSize(new java.awt.Dimension(60, 25));
        X0Textfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X0Textfield2ActionPerformed(evt);
            }
        });

        Y0Textfield2.setText("0");
        Y0Textfield2.setToolTipText("");
        Y0Textfield2.setPreferredSize(new java.awt.Dimension(60, 25));
        Y0Textfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y0Textfield2ActionPerformed(evt);
            }
        });

        Y1Textfield2.setText("0");
        Y1Textfield2.setToolTipText("");
        Y1Textfield2.setPreferredSize(new java.awt.Dimension(60, 25));
        Y1Textfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y1Textfield2ActionPerformed(evt);
            }
        });

        X1Textfield2.setText("0");
        X1Textfield2.setToolTipText("");
        X1Textfield2.setPreferredSize(new java.awt.Dimension(60, 25));
        X1Textfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X1Textfield2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Line 1");

        jLabel6.setText("Line 2");

        jLabel7.setText("x0");

        jLabel8.setText("y0");

        jLabel9.setText("x1");

        jLabel10.setText("y1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(X0Textfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(X0Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Y0Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Y0Textfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(X1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(X1Textfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Y1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Y1Textfield2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CalculateButton)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton)
                        .addGap(23, 23, 23)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Y1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(X1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Y0Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(X0Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Y1Textfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(X1Textfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Y0Textfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(X0Textfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(CalculateButton))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void X0TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X0TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_X0TextfieldActionPerformed

    private void Y0TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y0TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Y0TextfieldActionPerformed

    private void X1TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X1TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_X1TextfieldActionPerformed

    private void Y1TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y1TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Y1TextfieldActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        // TODO add your handling code here:
        
        
        EquationOfLine equationOfLine = new EquationOfLine(X0Textfield.getText(),
                Y0Textfield.getText(), X1Textfield.getText(), Y1Textfield.getText());
        EquationOfLine equationOfLine2 = new EquationOfLine(X0Textfield2.getText(),
                Y0Textfield2.getText(), X1Textfield2.getText(), Y1Textfield2.getText());
        
        Point2D intersect = equationOfLine.calcIntersect(equationOfLine2);
        double x = equationOfLine.rounding("###.#", intersect.getX());
        double y = equationOfLine.rounding("###.#", intersect.getY());
        
        textBox.append(equationOfLine.generateFormula("###.###"));
        textBox.append(equationOfLine2.generateFormula("###.###"));
        textBox.append("(" + String.valueOf(x) + "," + 
                String.valueOf(y)+")");
        
        EquationOfQuadratic equationOfQuadratic = new EquationOfQuadratic(1,0,0);
        
//        System.out.print(Arrays.toString(equationOfQuadratic.getrootPoints())+ "\n");
//        System.out.print(equationOfQuadratic.getQuadratic());
//        System.out.print(Arrays.toString(equationOfQuadratic.intersect(equationOfLine)));
//        
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void X0Textfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X0Textfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_X0Textfield2ActionPerformed

    private void Y0Textfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y0Textfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Y0Textfield2ActionPerformed

    private void Y1Textfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y1Textfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Y1Textfield2ActionPerformed

    private void X1Textfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X1Textfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_X1Textfield2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField X0Textfield;
    private javax.swing.JTextField X0Textfield2;
    private javax.swing.JTextField X1Textfield;
    private javax.swing.JTextField X1Textfield2;
    private javax.swing.JTextField Y0Textfield;
    private javax.swing.JTextField Y0Textfield2;
    private javax.swing.JTextField Y1Textfield;
    private javax.swing.JTextField Y1Textfield2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea textBox;
    // End of variables declaration//GEN-END:variables
}
